# Generated by Django 4.1.5 on 2023-01-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0002_transacao"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoria",
            options={"verbose_name_plural": "Categorias"},
        ),
        migrations.AlterModelOptions(
            name="transacao",
            options={"verbose_name_plural": "Transações"},
        ),
        migrations.AlterField(
            model_name="transacao",
            name="data",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="transacao",
            name="observacoes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
