# Generated by Django 4.1.5 on 2023-01-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0003_alter_categoria_options_alter_transacao_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transacao",
            name="data",
            field=models.DateTimeField(),
        ),
    ]
